### ISSUE TITLE
add MPS

### ISSUE THREAD

**Issue by PeterTheOne** [lab10-coop/minerva-tokenlists#6]
https://www.coingecko.com/en/coins/mt-pelerin-shares

Gnosis Chain https://blockscout.com/xdai/mainnet/token/0xfa57AA7beED63D03Aaf85fFd1753f5f6242588fb/token-transfers
Ethereum https://etherscan.io/address/0x96c645d3d3706f793ef52c19bbace441900ed47d

/cc @seliqui

**Comment by seliqui** [comment]
Done with commit [3239b18972f011b11c8fb59d6bfa36e5324e048b](https://github.com/lab10-coop/minerva-tokenlists/commit/3239b18972f011b11c8fb59d6bfa36e5324e048b)
